### ISSUE TITLE
About your problem with source maps

### ISSUE THREAD

**Issue by julienw** [davityle/davityle.github.io#1]
Hey !

I just read your post at https://davityle.github.io/post/why-im-not-switching-to-firefox/. I'm part of the devtools team at Firefox, and I'd like to file a bug about the issue you found with our source map implementation. We just redid all of this so it's not surprising that we still have bugs with edge cases :)

But then I need some more information about your issue. Here is how you can help:

1. have a STR to reproduce your issue: eg: first clone this, then run `npm install`, then `npm start`, then open Firefox on this URL, and open the debugger, and boom.
2. give the full stack trace for your error, or at least the file name + line number.
3. You may have more information in the browser console (it's in the "web development" submenu)

I'm sure the bug itself is easily fixable, but first we need more information ;)

Thanks !

**Comment by juliandescottes** [comment]
For the record I am currently investigating issues very similar to what is described here:

"Opening the dev tools and then loading the editor completely locked up all of Firefox except for, ironically, the dev tools."

In the dev mode of one of my side projects, I load scripts sequentially, which triggers a ton of mutations... and Firefox DevTools have a lot of trouble handling that at the moment. My webapp takes a minute to reload if the devtools are opened. Maybe this is a similar problem.

So if you also can give a bit more details about how your dev environment works, how many files you load, how you load them etc... I would love to try and fix this too!

**Comment by jasonLaster** [comment]
Hey!

I work on the debugger and would be happy to diagnose the source maps issue. We use webpack and have worked w/ the browserify folks as well. I'm sure we'll be able to get to bottom of it.

Come say hi in [slack](https://devtools-html-slack.herokuapp.com)!

**Comment by davityle** [comment]
@julienw I can try to find some time to find a smaller reproducable case but no gaurantees! 
@juliandescottes I believe we are approacing about 1,000,000 lines of code (unminified of course). This is split into around 3000 files. In order to keep the browser from having to fetch each of the files individually (which takes an eternity because of request throttling) they are all written to a single file that then uses the Google Closure Library to execute each file as it's own module with correct scoping etc. etc. This file ends up being around 25 MB. Besides that file there are other files that are loaded as well but I'm guessing they are pretty inconsequential compared to the editor source code. 
@jasonLaster I tried joining the slack channel but I never got the invite email. That's awesome that you love using Lucidchart! I'm going to share your comment internally if you don't mind.

**Comment by julienw** [comment]
Hey @davityle,

As a first step, could you give us the full error ? Especially including the filename + the line number ? Thanks :)
